# Generated by Django 5.2.1 on 2025-05-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seneca', '0002_application_comment_application_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='date',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
