# Generated by Django 5.2.1 on 2025-05-20 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seneca', '0003_video_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('rate', models.DecimalField(decimal_places=2, help_text='В процентах, например 8.50', max_digits=5, verbose_name='Годовая ставка (%)')),
            ],
        ),
    ]
